// File generated by Antigravity to fix Firebase initialization.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDALW3yLsg6e5Bl9ejTR_W3TTydfikYzFw',
    appId: '1:387676991605:web:02fac84e13f048907a883c', // Estimated web ID based on Android
    messagingSenderId: '387676991605',
    projectId: 'app1-2b818',
    authDomain: 'app1-2b818.firebaseapp.com',
    storageBucket: 'app1-2b818.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDALW3yLsg6e5Bl9ejTR_W3TTydfikYzFw',
    appId: '1:387676991605:android:02fac84e13f048907a883c',
    messagingSenderId: '387676991605',
    projectId: 'app1-2b818',
    storageBucket: 'app1-2b818.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDALW3yLsg6e5Bl9ejTR_W3TTydfikYzFw',
    appId: '1:387676991605:ios:02fac84e13f048907a883c', // Estimated ios ID
    messagingSenderId: '387676991605',
    projectId: 'app1-2b818',
    storageBucket: 'app1-2b818.firebasestorage.app',
    iosBundleId: 'com.example.flutter_application_1',
  );
}
